development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  pool: 5
  username: postgres
  password: password

test: &test
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
  pool: 5
  username: postgres
  password: password