development:
  adapter: postgresql
  encoding: utf8
  database: contacts_development
  pool: 5
  username: postgres
  password: password

test: &test
  adapter: postgresql
  encoding: utf8
  database: contacts_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: contacts_production
  pool: 5
  username: postgres
  password: password